// Canton SEO data for landing pages
// Each canton has unique content, premium stats, and targeted keywords

export interface CantonData {
  slug: string;
  name: string;
  nameDE: string; // Full German name
  abbreviation: string;
  hauptort: string;
  einwohner: string;
  praemienregionen: number;
  avgPraemie2026: number; // Average adult premium 2026
  avgPraemie2025: number; // Average adult premium 2025
  aenderungProzent: number; // Change %
  guenstigsteKasse: string;
  guenstigstePraemie: number;
  teuersteKasse: string;
  teuerstePraemie: number;
  sparpotenzial: number; // Max savings per year
  metaTitle: string;
  metaDescription: string;
  heroTitle: string;
  heroSubtitle: string;
  introText: string;
  besonderheiten: string[]; // Canton-specific facts
  topVersicherer: string[]; // Best insurers for this canton
  faqItems: { q: string; a: string }[];
}

export const CANTONS: CantonData[] = [
  {
    slug: "zuerich",
    name: "Zürich",
    nameDE: "Kanton Zürich",
    abbreviation: "ZH",
    hauptort: "Zürich",
    einwohner: "1'579'967",
    praemienregionen: 3,
    avgPraemie2026: 448.60,
    avgPraemie2025: 426.40,
    aenderungProzent: 5.2,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 300.90,
    teuersteKasse: "Supra",
    teuerstePraemie: 676.70,
    sparpotenzial: 4512,
    metaTitle: "Krankenkasse Zürich 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien im Kanton Zürich 2026 vergleichen. Günstigste Kasse ab CHF 300.90/Mt. Bis CHF 4'512 pro Jahr sparen. Offizielle BAG-Daten.",
    heroTitle: "Krankenkasse Zürich 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 4'512 pro Jahr sparen",
    introText: "Der Kanton Zürich hat mit über 1.5 Millionen Einwohnern die meisten Versicherten der Schweiz. Die durchschnittliche Krankenkassenprämie für Erwachsene liegt 2026 bei CHF 448.60 pro Monat – ein Anstieg von 5.2% gegenüber dem Vorjahr. Mit 3 Prämienregionen und grossen Unterschieden zwischen den Kassen lohnt sich ein Vergleich besonders.",
    besonderheiten: [
      "Grösster Kanton nach Einwohnerzahl – über 1.5 Millionen Versicherte",
      "3 Prämienregionen: Stadt Zürich, Agglomeration und ländliche Gebiete",
      "Prämien 14% über dem Schweizer Durchschnitt",
      "Viele HMO-Zentren in der Stadt – bis zu 25% günstiger",
      "Prämienverbilligung: Anspruch ab Einkommen unter CHF 54'400 (Einzelperson)",
    ],
    topVersicherer: ["Agrisano", "Concordia", "CSS", "ÖKK", "Swica"],
    faqItems: [
      {
        q: "Was kostet die günstigste Krankenkasse in Zürich 2026?",
        a: "Die günstigste Grundversicherung im Kanton Zürich kostet ab CHF 300.90 pro Monat (Erwachsene, höchste Franchise). Im Standardmodell mit Franchise CHF 300 beginnen die Prämien bei ca. CHF 450.",
      },
      {
        q: "Wie viel kann ich in Zürich durch einen Krankenkassenwechsel sparen?",
        a: "Die Differenz zwischen der teuersten und günstigsten Kasse beträgt bis zu CHF 376 pro Monat – das sind über CHF 4'500 pro Jahr. Im Durchschnitt sparen Wechsler CHF 800–1'200 jährlich.",
      },
      {
        q: "Welche Prämienregion gilt für mich in Zürich?",
        a: "Der Kanton Zürich hat 3 Prämienregionen. Die Stadt Zürich und Winterthur gehören zur teuersten Region 1. Vorstadtgemeinden zur Region 2, ländliche Gebiete zur Region 3. Geben Sie Ihre PLZ in unseren Rechner ein für die exakte Zuordnung.",
      },
      {
        q: "Habe ich Anspruch auf Prämienverbilligung in Zürich?",
        a: "Im Kanton Zürich haben Einzelpersonen mit einem steuerbaren Einkommen unter ca. CHF 54'400 Anspruch auf individuelle Prämienverbilligung (IPV). Für Familien gelten höhere Grenzen. Der Antrag läuft über die Sozialversicherungsanstalt (SVA) Zürich.",
      },
    ],
  },
  {
    slug: "bern",
    name: "Bern",
    nameDE: "Kanton Bern",
    abbreviation: "BE",
    hauptort: "Bern",
    einwohner: "1'043'132",
    praemienregionen: 3,
    avgPraemie2026: 401.50,
    avgPraemie2025: 383.70,
    aenderungProzent: 4.6,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 272.80,
    teuersteKasse: "Supra",
    teuerstePraemie: 589.60,
    sparpotenzial: 3802,
    metaTitle: "Krankenkasse Bern 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien im Kanton Bern 2026 vergleichen. Günstigste Kasse ab CHF 272.80/Mt. Bis CHF 3'802 pro Jahr sparen. Alle Kassen im Vergleich.",
    heroTitle: "Krankenkasse Bern 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'802 pro Jahr sparen",
    introText: "Der Kanton Bern ist der zweitgrösste Kanton der Schweiz. Die durchschnittliche Prämie für Erwachsene beträgt 2026 CHF 401.50 – leicht unter dem Schweizer Durchschnitt. Durch die 3 Prämienregionen und die grosse Anzahl an Versicherern gibt es deutliche Preisunterschiede.",
    besonderheiten: [
      "Zweitgrösster Kanton der Schweiz mit über 1 Million Einwohnern",
      "Prämien leicht unter dem Schweizer Durchschnitt",
      "3 Prämienregionen: Stadt Bern, Agglomeration und Oberland/Emmental",
      "Berner Oberland und Emmental oft in günstigerer Prämienregion",
      "Ausgleichskasse Bern für Prämienverbilligung zuständig",
    ],
    topVersicherer: ["Agrisano", "Visana", "KPT", "CSS", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die günstigste Krankenkasse in Bern 2026?",
        a: "Im Kanton Bern starten die günstigsten Prämien bei CHF 272.80 pro Monat für Erwachsene mit der höchsten Franchise. Standardmodell ab ca. CHF 380.",
      },
      {
        q: "Wie viele Prämienregionen hat der Kanton Bern?",
        a: "Bern hat 3 Prämienregionen. Die Stadt Bern und umliegende Gemeinden sind in der teuersten Region 1. Je ländlicher, desto günstiger die Prämien.",
      },
      {
        q: "Welche Krankenkassen sind in Bern besonders günstig?",
        a: "Agrisano, Visana und KPT gehören im Kanton Bern regelmässig zu den günstigsten Anbietern. Ein Vergleich lohnt sich, da die Rankings je nach Prämienregion, Alter und Franchise variieren.",
      },
    ],
  },
  {
    slug: "luzern",
    name: "Luzern",
    nameDE: "Kanton Luzern",
    abbreviation: "LU",
    hauptort: "Luzern",
    einwohner: "420'567",
    praemienregionen: 2,
    avgPraemie2026: 384.20,
    avgPraemie2025: 368.10,
    aenderungProzent: 4.4,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 261.50,
    teuersteKasse: "Supra",
    teuerstePraemie: 561.30,
    sparpotenzial: 3598,
    metaTitle: "Krankenkasse Luzern 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien im Kanton Luzern 2026 vergleichen. Günstigste Kasse ab CHF 261.50/Mt. Bis CHF 3'598 pro Jahr sparen.",
    heroTitle: "Krankenkasse Luzern 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'598 pro Jahr sparen",
    introText: "Der Kanton Luzern liegt beim Prämienniveau leicht unter dem Schweizer Durchschnitt. Mit 2 Prämienregionen und einer Prämienerhöhung von 4.4% lohnt sich ein Vergleich für 2026 besonders.",
    besonderheiten: [
      "2 Prämienregionen: Stadt Luzern und Umgebung vs. ländliche Gebiete",
      "Prämienniveau leicht unter dem Schweizer Durchschnitt",
      "Gutes Angebot an HMO- und Hausarztmodellen",
      "Prämienverbilligung über die AHV-Zweigstelle der Gemeinde",
    ],
    topVersicherer: ["Agrisano", "CSS", "Concordia", "ÖKK", "Helsana"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Luzern 2026?",
        a: "Die durchschnittliche Prämie im Kanton Luzern beträgt 2026 CHF 384.20. Die günstigste Kasse bietet Prämien ab CHF 261.50 pro Monat.",
      },
      {
        q: "Wie viel kann ich in Luzern sparen?",
        a: "Zwischen der günstigsten und teuersten Kasse liegen bis zu CHF 300 pro Monat – das sind über CHF 3'500 pro Jahr Sparpotenzial.",
      },
    ],
  },
  {
    slug: "uri",
    name: "Uri",
    nameDE: "Kanton Uri",
    abbreviation: "UR",
    hauptort: "Altdorf",
    einwohner: "37'047",
    praemienregionen: 1,
    avgPraemie2026: 358.40,
    avgPraemie2025: 343.80,
    aenderungProzent: 4.2,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 248.30,
    teuersteKasse: "Supra",
    teuerstePraemie: 528.90,
    sparpotenzial: 3367,
    metaTitle: "Krankenkasse Uri 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien im Kanton Uri 2026 vergleichen. Günstigste Kasse ab CHF 248.30/Mt. Offizielle BAG-Daten.",
    heroTitle: "Krankenkasse Uri 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'367 pro Jahr sparen",
    introText: "Der Kanton Uri gehört mit nur einer Prämienregion zu den übersichtlichsten Kantonen beim Krankenkassenvergleich. Die Prämien liegen unter dem Schweizer Durchschnitt.",
    besonderheiten: [
      "Nur 1 Prämienregion – einheitliche Prämien im ganzen Kanton",
      "Prämien deutlich unter dem Schweizer Durchschnitt",
      "Kleinster Kanton der Zentralschweiz",
    ],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Uri 2026?",
        a: "Die durchschnittliche Prämie beträgt CHF 358.40. Die günstigste Kasse ab CHF 248.30 pro Monat.",
      },
    ],
  },
  {
    slug: "schwyz",
    name: "Schwyz",
    nameDE: "Kanton Schwyz",
    abbreviation: "SZ",
    hauptort: "Schwyz",
    einwohner: "164'491",
    praemienregionen: 2,
    avgPraemie2026: 374.80,
    avgPraemie2025: 359.40,
    aenderungProzent: 4.3,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 254.70,
    teuersteKasse: "Supra",
    teuerstePraemie: 553.20,
    sparpotenzial: 3582,
    metaTitle: "Krankenkasse Schwyz 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien im Kanton Schwyz 2026 vergleichen. Ab CHF 254.70/Mt. Alle Versicherer im Vergleich.",
    heroTitle: "Krankenkasse Schwyz 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'582 pro Jahr sparen",
    introText: "Der Kanton Schwyz bietet mit 2 Prämienregionen moderate Prämien unter dem Schweizer Durchschnitt.",
    besonderheiten: [
      "2 Prämienregionen",
      "Prämien unter dem Schweizer Durchschnitt",
      "Steuergünstiger Kanton – kombiniert mit günstigen Prämien attraktiv",
    ],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia", "Swica"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Schwyz?",
        a: "Durchschnittlich CHF 374.80 pro Monat. Günstigste ab CHF 254.70.",
      },
    ],
  },
  {
    slug: "obwalden",
    name: "Obwalden",
    nameDE: "Kanton Obwalden",
    abbreviation: "OW",
    hauptort: "Sarnen",
    einwohner: "38'541",
    praemienregionen: 1,
    avgPraemie2026: 352.10,
    avgPraemie2025: 337.80,
    aenderungProzent: 4.2,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 242.60,
    teuersteKasse: "Supra",
    teuerstePraemie: 518.40,
    sparpotenzial: 3310,
    metaTitle: "Krankenkasse Obwalden 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Obwalden 2026. Ab CHF 242.60/Mt. Jetzt vergleichen.",
    heroTitle: "Krankenkasse Obwalden 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'310 pro Jahr sparen",
    introText: "Der Kanton Obwalden hat nur eine Prämienregion und gehört zu den günstigeren Kantonen der Schweiz.",
    besonderheiten: [
      "Nur 1 Prämienregion",
      "Einer der günstigsten Kantone der Zentralschweiz",
      "Tiefe Steuern kombiniert mit moderaten Prämien",
    ],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Obwalden?",
        a: "Durchschnittlich CHF 352.10/Mt. Günstigste ab CHF 242.60.",
      },
    ],
  },
  {
    slug: "nidwalden",
    name: "Nidwalden",
    nameDE: "Kanton Nidwalden",
    abbreviation: "NW",
    hauptort: "Stans",
    einwohner: "43'520",
    praemienregionen: 1,
    avgPraemie2026: 348.70,
    avgPraemie2025: 334.90,
    aenderungProzent: 4.1,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 240.10,
    teuersteKasse: "Supra",
    teuerstePraemie: 512.60,
    sparpotenzial: 3270,
    metaTitle: "Krankenkasse Nidwalden 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Nidwalden 2026. Ab CHF 240.10/Mt. Jetzt vergleichen.",
    heroTitle: "Krankenkasse Nidwalden 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'270 pro Jahr sparen",
    introText: "Nidwalden gehört zu den günstigsten Kantonen der Schweiz bei den Krankenkassenprämien.",
    besonderheiten: ["Nur 1 Prämienregion", "Einer der günstigsten Kantone der Schweiz"],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Nidwalden?",
        a: "Durchschnittlich CHF 348.70/Mt. Günstigste ab CHF 240.10.",
      },
    ],
  },
  {
    slug: "glarus",
    name: "Glarus",
    nameDE: "Kanton Glarus",
    abbreviation: "GL",
    hauptort: "Glarus",
    einwohner: "41'097",
    praemienregionen: 1,
    avgPraemie2026: 362.30,
    avgPraemie2025: 347.50,
    aenderungProzent: 4.3,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 250.40,
    teuersteKasse: "Supra",
    teuerstePraemie: 534.80,
    sparpotenzial: 3413,
    metaTitle: "Krankenkasse Glarus 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Glarus 2026. Ab CHF 250.40/Mt. Jetzt vergleichen.",
    heroTitle: "Krankenkasse Glarus 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'413 pro Jahr sparen",
    introText: "Der Kanton Glarus hat nur eine Prämienregion und bietet moderate Krankenkassenprämien.",
    besonderheiten: ["Nur 1 Prämienregion", "Moderate Prämien in der Ostschweiz"],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Glarus?",
        a: "Durchschnittlich CHF 362.30/Mt. Günstigste ab CHF 250.40.",
      },
    ],
  },
  {
    slug: "zug",
    name: "Zug",
    nameDE: "Kanton Zug",
    abbreviation: "ZG",
    hauptort: "Zug",
    einwohner: "131'164",
    praemienregionen: 1,
    avgPraemie2026: 378.90,
    avgPraemie2025: 363.50,
    aenderungProzent: 4.2,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 258.20,
    teuersteKasse: "Supra",
    teuerstePraemie: 558.40,
    sparpotenzial: 3602,
    metaTitle: "Krankenkasse Zug 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Zug 2026. Ab CHF 258.20/Mt. Bis CHF 3'602 sparen.",
    heroTitle: "Krankenkasse Zug 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'602 pro Jahr sparen",
    introText: "Der Kanton Zug kombiniert die tiefsten Steuern der Schweiz mit moderaten Krankenkassenprämien. Mit einer Prämienregion ist der Vergleich unkompliziert.",
    besonderheiten: [
      "Nur 1 Prämienregion",
      "Tiefste Steuern der Schweiz – Prämienvergleich maximiert die Ersparnis",
      "Hohe Dichte an internationalen Unternehmen",
    ],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Swica", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Zug?",
        a: "Durchschnittlich CHF 378.90/Mt. Günstigste ab CHF 258.20.",
      },
    ],
  },
  {
    slug: "freiburg",
    name: "Freiburg",
    nameDE: "Kanton Freiburg",
    abbreviation: "FR",
    hauptort: "Freiburg",
    einwohner: "328'305",
    praemienregionen: 2,
    avgPraemie2026: 378.40,
    avgPraemie2025: 362.80,
    aenderungProzent: 4.3,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 256.90,
    teuersteKasse: "Supra",
    teuerstePraemie: 555.70,
    sparpotenzial: 3586,
    metaTitle: "Krankenkasse Freiburg 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Freiburg 2026. Ab CHF 256.90/Mt. Deutsch & Französisch.",
    heroTitle: "Krankenkasse Freiburg 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'586 pro Jahr sparen",
    introText: "Der zweisprachige Kanton Freiburg bietet mit 2 Prämienregionen moderate Krankenkassenprämien unter dem Schweizer Durchschnitt.",
    besonderheiten: [
      "Zweisprachiger Kanton (Deutsch/Französisch)",
      "2 Prämienregionen",
      "Prämien unter dem Schweizer Durchschnitt",
    ],
    topVersicherer: ["Agrisano", "Groupe Mutuel", "CSS", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Freiburg?",
        a: "Durchschnittlich CHF 378.40/Mt. Günstigste ab CHF 256.90.",
      },
    ],
  },
  {
    slug: "solothurn",
    name: "Solothurn",
    nameDE: "Kanton Solothurn",
    abbreviation: "SO",
    hauptort: "Solothurn",
    einwohner: "280'245",
    praemienregionen: 2,
    avgPraemie2026: 398.60,
    avgPraemie2025: 381.90,
    aenderungProzent: 4.4,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 270.40,
    teuersteKasse: "Supra",
    teuerstePraemie: 586.30,
    sparpotenzial: 3791,
    metaTitle: "Krankenkasse Solothurn 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Solothurn 2026. Ab CHF 270.40/Mt. Jetzt vergleichen.",
    heroTitle: "Krankenkasse Solothurn 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'791 pro Jahr sparen",
    introText: "Der Kanton Solothurn liegt beim Prämienniveau nahe am Schweizer Durchschnitt. Mit 2 Prämienregionen gibt es regionale Unterschiede.",
    besonderheiten: [
      "2 Prämienregionen",
      "Prämien nahe am Schweizer Durchschnitt",
      "Gute Anbindung an Basel und Bern",
    ],
    topVersicherer: ["Agrisano", "CSS", "Visana", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Solothurn?",
        a: "Durchschnittlich CHF 398.60/Mt. Günstigste ab CHF 270.40.",
      },
    ],
  },
  {
    slug: "basel-stadt",
    name: "Basel-Stadt",
    nameDE: "Kanton Basel-Stadt",
    abbreviation: "BS",
    hauptort: "Basel",
    einwohner: "196'735",
    praemienregionen: 1,
    avgPraemie2026: 468.30,
    avgPraemie2025: 446.80,
    aenderungProzent: 4.8,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 318.50,
    teuersteKasse: "Supra",
    teuerstePraemie: 698.20,
    sparpotenzial: 4556,
    metaTitle: "Krankenkasse Basel-Stadt 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Basel-Stadt 2026. Teuerster Kanton! Ab CHF 318.50/Mt. Vergleich lohnt sich besonders.",
    heroTitle: "Krankenkasse Basel-Stadt 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 4'556 pro Jahr sparen",
    introText: "Basel-Stadt gehört zu den teuersten Kantonen bei den Krankenkassenprämien. Umso mehr lohnt sich ein Vergleich – die Unterschiede zwischen den Kassen sind enorm.",
    besonderheiten: [
      "Einer der teuersten Kantone bei Krankenkassenprämien",
      "Nur 1 Prämienregion",
      "Enormes Sparpotenzial durch grosse Preisunterschiede",
      "Pharma- und Gesundheitsstandort",
    ],
    topVersicherer: ["Agrisano", "CSS", "Concordia", "ÖKK", "Swica"],
    faqItems: [
      {
        q: "Warum sind die Prämien in Basel-Stadt so hoch?",
        a: "Basel-Stadt hat eine hohe Ärztedichte und viele Spezialisten. Das führt zu höheren Gesundheitskosten und damit zu höheren Prämien. Ein Wechsel zu einem günstigeren Anbieter spart daher besonders viel.",
      },
    ],
  },
  {
    slug: "basel-landschaft",
    name: "Basel-Landschaft",
    nameDE: "Kanton Basel-Landschaft",
    abbreviation: "BL",
    hauptort: "Liestal",
    einwohner: "293'881",
    praemienregionen: 2,
    avgPraemie2026: 442.10,
    avgPraemie2025: 422.50,
    aenderungProzent: 4.6,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 298.70,
    teuersteKasse: "Supra",
    teuerstePraemie: 658.40,
    sparpotenzial: 4316,
    metaTitle: "Krankenkasse Basel-Landschaft 2026 – Prämien vergleichen",
    metaDescription: "Krankenkassenprämien Basel-Landschaft 2026. Ab CHF 298.70/Mt. Alle Kassen im Vergleich.",
    heroTitle: "Krankenkasse Basel-Landschaft 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 4'316 pro Jahr sparen",
    introText: "Der Kanton Basel-Landschaft hat mit 2 Prämienregionen etwas tiefere Prämien als der Stadtkanton Basel-Stadt, liegt aber immer noch über dem Schweizer Durchschnitt.",
    besonderheiten: [
      "2 Prämienregionen",
      "Günstiger als Basel-Stadt, aber über dem CH-Durchschnitt",
      "Nähe zu Basel – viele HMO-Angebote verfügbar",
    ],
    topVersicherer: ["Agrisano", "CSS", "Concordia", "ÖKK"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Basel-Landschaft?",
        a: "Durchschnittlich CHF 442.10/Mt. Günstigste ab CHF 298.70.",
      },
    ],
  },
  {
    slug: "schaffhausen",
    name: "Schaffhausen",
    nameDE: "Kanton Schaffhausen",
    abbreviation: "SH",
    hauptort: "Schaffhausen",
    einwohner: "84'246",
    praemienregionen: 1,
    avgPraemie2026: 392.80,
    avgPraemie2025: 376.70,
    aenderungProzent: 4.3,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 267.30,
    teuersteKasse: "Supra",
    teuerstePraemie: 579.40,
    sparpotenzial: 3745,
    metaTitle: "Krankenkasse Schaffhausen 2026 – Prämien vergleichen",
    metaDescription: "Krankenkassenprämien Kanton Schaffhausen 2026. Ab CHF 267.30/Mt. Jetzt vergleichen.",
    heroTitle: "Krankenkasse Schaffhausen 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'745 pro Jahr sparen",
    introText: "Schaffhausen hat als nördlichster Kanton der Schweiz nur eine Prämienregion und liegt nahe am Schweizer Durchschnitt.",
    besonderheiten: ["Nur 1 Prämienregion", "Nördlichster Kanton der Schweiz"],
    topVersicherer: ["Agrisano", "CSS", "Concordia", "ÖKK"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Schaffhausen?",
        a: "Durchschnittlich CHF 392.80/Mt. Günstigste ab CHF 267.30.",
      },
    ],
  },
  {
    slug: "appenzell-ausserrhoden",
    name: "Appenzell Ausserrhoden",
    nameDE: "Kanton Appenzell Ausserrhoden",
    abbreviation: "AR",
    hauptort: "Herisau",
    einwohner: "55'585",
    praemienregionen: 1,
    avgPraemie2026: 366.40,
    avgPraemie2025: 351.80,
    aenderungProzent: 4.2,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 252.10,
    teuersteKasse: "Supra",
    teuerstePraemie: 540.60,
    sparpotenzial: 3462,
    metaTitle: "Krankenkasse Appenzell Ausserrhoden 2026 – Vergleich",
    metaDescription: "Krankenkassenprämien Appenzell Ausserrhoden 2026. Ab CHF 252.10/Mt.",
    heroTitle: "Krankenkasse Appenzell AR 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'462 pro Jahr sparen",
    introText: "Appenzell Ausserrhoden gehört zu den günstigeren Kantonen bei den Krankenkassenprämien.",
    besonderheiten: ["Nur 1 Prämienregion", "Günstige Prämien in der Ostschweiz"],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Appenzell AR?",
        a: "Durchschnittlich CHF 366.40/Mt. Günstigste ab CHF 252.10.",
      },
    ],
  },
  {
    slug: "appenzell-innerrhoden",
    name: "Appenzell Innerrhoden",
    nameDE: "Kanton Appenzell Innerrhoden",
    abbreviation: "AI",
    hauptort: "Appenzell",
    einwohner: "16'293",
    praemienregionen: 1,
    avgPraemie2026: 340.20,
    avgPraemie2025: 326.90,
    aenderungProzent: 4.1,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 234.60,
    teuersteKasse: "Supra",
    teuerstePraemie: 502.10,
    sparpotenzial: 3210,
    metaTitle: "Krankenkasse Appenzell Innerrhoden 2026 – Vergleich",
    metaDescription: "Krankenkassenprämien Appenzell Innerrhoden 2026. Ab CHF 234.60/Mt. Günstigster Kanton!",
    heroTitle: "Krankenkasse Appenzell IR 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'210 pro Jahr sparen",
    introText: "Appenzell Innerrhoden gehört zu den günstigsten Kantonen der Schweiz bei den Krankenkassenprämien.",
    besonderheiten: [
      "Nur 1 Prämienregion",
      "Einer der günstigsten Kantone der Schweiz",
      "Kleinster Kanton nach Einwohnerzahl",
    ],
    topVersicherer: ["Agrisano", "CSS", "ÖKK"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Appenzell IR?",
        a: "Durchschnittlich CHF 340.20/Mt – einer der tiefsten Werte der Schweiz.",
      },
    ],
  },
  {
    slug: "st-gallen",
    name: "St. Gallen",
    nameDE: "Kanton St. Gallen",
    abbreviation: "SG",
    hauptort: "St. Gallen",
    einwohner: "519'245",
    praemienregionen: 2,
    avgPraemie2026: 382.50,
    avgPraemie2025: 367.10,
    aenderungProzent: 4.2,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 260.80,
    teuersteKasse: "Supra",
    teuerstePraemie: 564.20,
    sparpotenzial: 3641,
    metaTitle: "Krankenkasse St. Gallen 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton St. Gallen 2026. Ab CHF 260.80/Mt. Alle Versicherer verglichen.",
    heroTitle: "Krankenkasse St. Gallen 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'641 pro Jahr sparen",
    introText: "Der Kanton St. Gallen ist der grösste Ostschweizer Kanton und bietet mit 2 Prämienregionen leicht unterdurchschnittliche Prämien.",
    besonderheiten: [
      "2 Prämienregionen",
      "Grösster Ostschweizer Kanton",
      "Prämien leicht unter dem CH-Durchschnitt",
    ],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia", "Swica"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in St. Gallen?",
        a: "Durchschnittlich CHF 382.50/Mt. Günstigste ab CHF 260.80.",
      },
    ],
  },
  {
    slug: "graubuenden",
    name: "Graubünden",
    nameDE: "Kanton Graubünden",
    abbreviation: "GR",
    hauptort: "Chur",
    einwohner: "200'096",
    praemienregionen: 2,
    avgPraemie2026: 356.70,
    avgPraemie2025: 342.50,
    aenderungProzent: 4.1,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 246.90,
    teuersteKasse: "Supra",
    teuerstePraemie: 526.80,
    sparpotenzial: 3359,
    metaTitle: "Krankenkasse Graubünden 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Graubünden 2026. Ab CHF 246.90/Mt. Vergleichen & sparen.",
    heroTitle: "Krankenkasse Graubünden 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'359 pro Jahr sparen",
    introText: "Der grösste Kanton der Schweiz (Fläche) bietet günstige Krankenkassenprämien unter dem Schweizer Durchschnitt.",
    besonderheiten: [
      "2 Prämienregionen",
      "Flächenmässig grösster Kanton",
      "Günstige Prämien – unter dem Durchschnitt",
      "Dreisprachig (Deutsch, Italienisch, Romanisch)",
    ],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Graubünden?",
        a: "Durchschnittlich CHF 356.70/Mt. Günstigste ab CHF 246.90.",
      },
    ],
  },
  {
    slug: "aargau",
    name: "Aargau",
    nameDE: "Kanton Aargau",
    abbreviation: "AG",
    hauptort: "Aarau",
    einwohner: "703'086",
    praemienregionen: 3,
    avgPraemie2026: 410.30,
    avgPraemie2025: 393.20,
    aenderungProzent: 4.3,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 278.40,
    teuersteKasse: "Supra",
    teuerstePraemie: 604.50,
    sparpotenzial: 3913,
    metaTitle: "Krankenkasse Aargau 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Aargau 2026. Ab CHF 278.40/Mt. Bis CHF 3'913 sparen.",
    heroTitle: "Krankenkasse Aargau 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'913 pro Jahr sparen",
    introText: "Der Kanton Aargau hat mit 3 Prämienregionen und über 700'000 Einwohnern ein vielfältiges Prämienlandschaft. Die Prämien liegen leicht über dem Schweizer Durchschnitt.",
    besonderheiten: [
      "3 Prämienregionen",
      "Viertgrösster Kanton nach Einwohnerzahl",
      "Prämien leicht über dem CH-Durchschnitt",
      "Nähe zu Zürich – Region beeinflusst Prämien",
    ],
    topVersicherer: ["Agrisano", "CSS", "Concordia", "ÖKK", "Swica"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse im Aargau?",
        a: "Durchschnittlich CHF 410.30/Mt. Je nach Prämienregion variieren die Prämien stark.",
      },
    ],
  },
  {
    slug: "thurgau",
    name: "Thurgau",
    nameDE: "Kanton Thurgau",
    abbreviation: "TG",
    hauptort: "Frauenfeld",
    einwohner: "283'056",
    praemienregionen: 1,
    avgPraemie2026: 374.60,
    avgPraemie2025: 359.70,
    aenderungProzent: 4.1,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 255.80,
    teuersteKasse: "Supra",
    teuerstePraemie: 552.10,
    sparpotenzial: 3556,
    metaTitle: "Krankenkasse Thurgau 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Thurgau 2026. Ab CHF 255.80/Mt. Jetzt vergleichen.",
    heroTitle: "Krankenkasse Thurgau 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'556 pro Jahr sparen",
    introText: "Der Kanton Thurgau bietet mit nur einer Prämienregion einheitliche und günstige Krankenkassenprämien.",
    besonderheiten: ["Nur 1 Prämienregion", "Günstige Prämien – unter dem CH-Durchschnitt"],
    topVersicherer: ["Agrisano", "CSS", "ÖKK", "Concordia", "Swica"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse im Thurgau?",
        a: "Durchschnittlich CHF 374.60/Mt. Günstigste ab CHF 255.80.",
      },
    ],
  },
  {
    slug: "tessin",
    name: "Tessin",
    nameDE: "Kanton Tessin",
    abbreviation: "TI",
    hauptort: "Bellinzona",
    einwohner: "354'375",
    praemienregionen: 2,
    avgPraemie2026: 428.60,
    avgPraemie2025: 410.30,
    aenderungProzent: 4.5,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 290.40,
    teuersteKasse: "Supra",
    teuerstePraemie: 638.70,
    sparpotenzial: 4180,
    metaTitle: "Cassa malati Ticino 2026 – Krankenkasse Tessin vergleichen",
    metaDescription: "Krankenkassenprämien Kanton Tessin (Ticino) 2026. Ab CHF 290.40/Mt. Prämien vergleichen.",
    heroTitle: "Krankenkasse Tessin 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 4'180 pro Jahr sparen",
    introText: "Das Tessin hat mit 2 Prämienregionen überdurchschnittliche Krankenkassenprämien. Aufgrund der hohen Gesundheitskosten im Kanton lohnt sich ein Vergleich besonders.",
    besonderheiten: [
      "2 Prämienregionen",
      "Überdurchschnittliche Prämien",
      "Italienischsprachiger Kanton",
      "Hohe Gesundheitskosten – Vergleich lohnt sich besonders",
    ],
    topVersicherer: ["Agrisano", "Assura", "Groupe Mutuel", "CSS"],
    faqItems: [
      {
        q: "Warum sind die Prämien im Tessin höher?",
        a: "Das Tessin hat höhere Gesundheitskosten pro Kopf als der Schweizer Durchschnitt, was sich in höheren Prämien niederschlägt.",
      },
    ],
  },
  {
    slug: "waadt",
    name: "Waadt",
    nameDE: "Kanton Waadt",
    abbreviation: "VD",
    hauptort: "Lausanne",
    einwohner: "815'300",
    praemienregionen: 3,
    avgPraemie2026: 438.90,
    avgPraemie2025: 419.70,
    aenderungProzent: 4.6,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 296.80,
    teuersteKasse: "Supra",
    teuerstePraemie: 654.30,
    sparpotenzial: 4290,
    metaTitle: "Krankenkasse Waadt (Vaud) 2026 – Prämien vergleichen",
    metaDescription: "Krankenkassenprämien Kanton Waadt 2026. Ab CHF 296.80/Mt. Bis CHF 4'290 sparen.",
    heroTitle: "Krankenkasse Waadt 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 4'290 pro Jahr sparen",
    introText: "Der Kanton Waadt ist der grösste Westschweizer Kanton und hat mit 3 Prämienregionen überdurchschnittliche Prämien.",
    besonderheiten: [
      "3 Prämienregionen",
      "Grösster Westschweizer Kanton",
      "Überdurchschnittliche Prämien",
      "Französischsprachig",
    ],
    topVersicherer: ["Agrisano", "Assura", "Groupe Mutuel", "CSS"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse im Kanton Waadt?",
        a: "Durchschnittlich CHF 438.90/Mt. Günstigste ab CHF 296.80.",
      },
    ],
  },
  {
    slug: "wallis",
    name: "Wallis",
    nameDE: "Kanton Wallis",
    abbreviation: "VS",
    hauptort: "Sion",
    einwohner: "348'503",
    praemienregionen: 2,
    avgPraemie2026: 376.20,
    avgPraemie2025: 361.30,
    aenderungProzent: 4.1,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 258.40,
    teuersteKasse: "Supra",
    teuerstePraemie: 554.80,
    sparpotenzial: 3557,
    metaTitle: "Krankenkasse Wallis 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Wallis (Valais) 2026. Ab CHF 258.40/Mt.",
    heroTitle: "Krankenkasse Wallis 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'557 pro Jahr sparen",
    introText: "Das Wallis bietet mit 2 Prämienregionen moderate Krankenkassenprämien unter dem Schweizer Durchschnitt.",
    besonderheiten: [
      "2 Prämienregionen",
      "Zweisprachig (Deutsch/Französisch)",
      "Prämien unter dem CH-Durchschnitt",
    ],
    topVersicherer: ["Agrisano", "Groupe Mutuel", "CSS", "Assura"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse im Wallis?",
        a: "Durchschnittlich CHF 376.20/Mt. Günstigste ab CHF 258.40.",
      },
    ],
  },
  {
    slug: "neuenburg",
    name: "Neuenburg",
    nameDE: "Kanton Neuenburg",
    abbreviation: "NE",
    hauptort: "Neuenburg",
    einwohner: "176'850",
    praemienregionen: 1,
    avgPraemie2026: 420.80,
    avgPraemie2025: 403.10,
    aenderungProzent: 4.4,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 286.30,
    teuersteKasse: "Supra",
    teuerstePraemie: 622.50,
    sparpotenzial: 4034,
    metaTitle: "Krankenkasse Neuenburg 2026 – Prämien vergleichen",
    metaDescription: "Krankenkassenprämien Neuenburg (Neuchâtel) 2026. Ab CHF 286.30/Mt.",
    heroTitle: "Krankenkasse Neuenburg 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 4'034 pro Jahr sparen",
    introText: "Der Kanton Neuenburg hat nur eine Prämienregion und überdurchschnittliche Krankenkassenprämien.",
    besonderheiten: ["Nur 1 Prämienregion", "Überdurchschnittliche Prämien", "Französischsprachig"],
    topVersicherer: ["Agrisano", "Assura", "Groupe Mutuel", "CSS"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse in Neuenburg?",
        a: "Durchschnittlich CHF 420.80/Mt. Günstigste ab CHF 286.30.",
      },
    ],
  },
  {
    slug: "genf",
    name: "Genf",
    nameDE: "Kanton Genf",
    abbreviation: "GE",
    hauptort: "Genf",
    einwohner: "504'128",
    praemienregionen: 1,
    avgPraemie2026: 492.70,
    avgPraemie2025: 470.40,
    aenderungProzent: 4.7,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 336.20,
    teuersteKasse: "Supra",
    teuerstePraemie: 732.80,
    sparpotenzial: 4759,
    metaTitle: "Krankenkasse Genf 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Genf (Genève) 2026. Teuerster Kanton! Ab CHF 336.20/Mt. Vergleich lohnt sich.",
    heroTitle: "Krankenkasse Genf 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 4'759 pro Jahr sparen",
    introText: "Genf ist der teuerste Kanton der Schweiz bei den Krankenkassenprämien. Die durchschnittliche Prämie liegt 2026 bei CHF 492.70 – ein Vergleich ist hier Pflicht.",
    besonderheiten: [
      "Teuerster Kanton bei Krankenkassenprämien",
      "Nur 1 Prämienregion",
      "Enormes Sparpotenzial – bis CHF 4'759 pro Jahr",
      "Hohe Ärztedichte und Gesundheitskosten",
      "Französischsprachig",
    ],
    topVersicherer: ["Agrisano", "Assura", "Groupe Mutuel", "CSS"],
    faqItems: [
      {
        q: "Warum ist Genf der teuerste Kanton?",
        a: "Genf hat die höchste Ärztedichte und die höchsten Gesundheitskosten pro Kopf der Schweiz. Das führt zu den schweizweit höchsten Krankenkassenprämien.",
      },
      {
        q: "Wie viel kann ich in Genf sparen?",
        a: "Bis zu CHF 4'759 pro Jahr! Die Unterschiede zwischen den Kassen sind in Genf besonders gross.",
      },
    ],
  },
  {
    slug: "jura",
    name: "Jura",
    nameDE: "Kanton Jura",
    abbreviation: "JU",
    hauptort: "Delémont",
    einwohner: "73'709",
    praemienregionen: 1,
    avgPraemie2026: 398.40,
    avgPraemie2025: 382.30,
    aenderungProzent: 4.2,
    guenstigsteKasse: "Agrisano",
    guenstigstePraemie: 271.80,
    teuersteKasse: "Supra",
    teuerstePraemie: 588.20,
    sparpotenzial: 3797,
    metaTitle: "Krankenkasse Jura 2026 – Prämien vergleichen & sparen",
    metaDescription: "Krankenkassenprämien Kanton Jura 2026. Ab CHF 271.80/Mt. Jetzt vergleichen.",
    heroTitle: "Krankenkasse Jura 2026",
    heroSubtitle: "Prämien vergleichen und bis zu CHF 3'797 pro Jahr sparen",
    introText: "Der jüngste Kanton der Schweiz hat nur eine Prämienregion und liegt nahe am Schweizer Durchschnitt.",
    besonderheiten: [
      "Nur 1 Prämienregion",
      "Jüngster Kanton der Schweiz (gegründet 1979)",
      "Französischsprachig",
    ],
    topVersicherer: ["Agrisano", "Assura", "Groupe Mutuel", "CSS"],
    faqItems: [
      {
        q: "Was kostet die Krankenkasse im Jura?",
        a: "Durchschnittlich CHF 398.40/Mt. Günstigste ab CHF 271.80.",
      },
    ],
  },
];

// Utility: Get canton by slug
export function getCantonBySlug(slug: string): CantonData | undefined {
  return CANTONS.find((c) => c.slug === slug);
}

// Utility: Get all canton slugs for static generation
export function getAllCantonSlugs(): string[] {
  return CANTONS.map((c) => c.slug);
}

// Format CHF values
export function formatCHF(value: number): string {
  return `CHF ${value.toLocaleString("de-CH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}
